public class Cadyof {
    public static void main() {
        System.out.println("mejpp");
        System.out.println("kngty");
        System.out.println("kmcnq");
        System.out.println("bhbvu");
        System.out.println("aemiq");
        System.out.println("kutyf");
        System.out.println("fanav");
        System.out.println("bfvef");
        System.out.println("rebim");
        System.out.println("blgce");
        System.out.println("gpbgu");
        System.out.println("aidiw");
        System.out.println("yqmgi");
        System.out.println("qyydq");
        System.out.println("hwpia");
        System.out.println("vbssp");
        System.out.println("qgucv");
        System.out.println("igaly");
        System.out.println("xhuwg");
        System.out.println("pvbog");
        System.out.println("qlrus");
        System.out.println("atkcb");
        System.out.println("fbxtm");
        System.out.println("bmasa");
        System.out.println("yyfmi");
        System.out.println("whfkk");
        System.out.println("slvfe");
        System.out.println("lveyd");
        System.out.println("gvhud");
        System.out.println("qnwip");
        System.out.println("ahyss");
        System.out.println("xstjg");
        System.out.println("tqsdr");
        System.out.println("jurlx");
        System.out.println("oyjiv");
        System.out.println("ppdiv");
        System.out.println("kdadl");
        System.out.println("uffrt");
        System.out.println("jubvh");
        System.out.println("agfvb");
        System.out.println("imoiv");
        System.out.println("hcsag");
        System.out.println("tfnfa");
    }
}
